//////////// THIS FILE MUST BE CREATED BY EXECUTING WriteAttributeDefinitionFile ////////////
//////////// DO NOT MODIFY THIS FILE MANUALLY ///////////////////////////////////////////////

#ifndef __NOMAD_4_0_EVALATTRIBUTESDEFINITION__
#define __NOMAD_4_0_EVALATTRIBUTESDEFINITION__

_definition = {
{ "BB_EVAL_FORMAT",  "NOMAD::ArrayOfDouble",  "-",  " Format of the doubles sent to the blackbox evaluator ",  " \n  \n . BB_EVAL_FORMAT is computed from the BB_INPUT_TYPE parameter. \n  \n . Gives the format precision for doubles sent to blackbox evaluator. \n  \n . CANNOT BE MODIFIED BY USER. Internal parameter. \n  \n . No default value.\n\n",  "  internal  "  , "false" , "false" , "true" },
{ "BB_EXE",  "std::string",  "",  " Blackbox executable ",  " \n  \n . Blackbox executable name \n  \n . List of strings \n  \n . Required for batch mode \n  \n . Unused in library mode \n  \n . One executable can give several outputs \n  \n . Use \' or \", and \'$\', to specify names or commands with spaces \n  \n . When the \'$\' character is put in first position of a string, it is \n   considered as global and no path will be added \n  \n . Examples \n     . BB_EXE bb.exe \n     . BB_EXE \'$nice bb.exe\' \n     . BB_EXE \'$python bb.py\' \n  \n . Default: Empty string.\n\n",  "  basic blackbox blackboxes bb exe executable executables binary output outputs batch  "  , "false" , "false" , "true" },
{ "BB_OUTPUT_TYPE",  "NOMAD::BBOutputTypeList",  "OBJ",  " Type of outputs provided by the blackboxes ",  " \n  \n . Blackbox output types \n  \n . List of types for each blackbox output \n  \n . Available types \n     . OBJ       : objective value to minimize (define twice for bi-objective) \n     . PB        : constraint <= 0 treated with Progressive Barrier (PB) \n     . CSTR      : same as 'PB' \n     . EB        : constraint <= 0 treated with Extreme Barrier (EB) \n     . F         : constraint <= 0 treated with Filter \n     . NOTHING   : this output is ignored \n     . EXTRA_O   : same as 'NOTHING' \n     .  -        : same as 'NOTHING' \n  \n . Equality constraints are not natively supported \n  \n . See parameters LOWER_BOUND and UPPER_BOUND for bound constraints \n  \n . Examples \n     . BB_EXE bb.exe                   # these two lines define \n     . BB_OUTPUT_TYPE OBJ EB EB        # that bb.exe outputs three values \n  \n . Default: OBJ\n\n",  "  basic bb exe blackbox blackboxs output outputs constraint constraints type types  "  , "false" , "false" , "true" },
{ "SURROGATE_EXE",  "std::string",  "",  " Static surrogate executable ",  " \n . To indicate a static surrogate executable \n  \n . List of strings \n  \n . Surrogate executable must have the same number of outputs as blackbox  \n     executable, defined by BB_OUTPUT_TYPE. \n  \n . Example \n     SURROGATE_EXE surrogate.exe     # surrogate.exe is a static surrogate executable \n                                     # for BB_EXE \n . Default: Empty string.\n\n",  "  advanced static surrogate executable  "  , "true" , "false" , "true" } };

#endif
